// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsuc30l3L6Fr69fxn73M-lT2WNDT22kLM',
    appId: '1:765957471616:web:cd6b2d9b27d6867ad41565',
    messagingSenderId: '765957471616',
    projectId: 'fruit-hub-da7cf',
    authDomain: 'fruit-hub-da7cf.firebaseapp.com',
    storageBucket: 'fruit-hub-da7cf.firebasestorage.app',
    measurementId: 'G-9Y0E1SQ31Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5nmoJv_7EJK8hwmo3jdhZBSKWL_NE8gw',
    appId: '1:765957471616:android:875aad7101fa6d77d41565',
    messagingSenderId: '765957471616',
    projectId: 'fruit-hub-da7cf',
    storageBucket: 'fruit-hub-da7cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASqLiLJAG1Uj3aCIyv1Bzp5fSS9NpHJNk',
    appId: '1:765957471616:ios:8f310333769272d5d41565',
    messagingSenderId: '765957471616',
    projectId: 'fruit-hub-da7cf',
    storageBucket: 'fruit-hub-da7cf.firebasestorage.app',
    iosBundleId: 'com.example.fruitesECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASqLiLJAG1Uj3aCIyv1Bzp5fSS9NpHJNk',
    appId: '1:765957471616:ios:8f310333769272d5d41565',
    messagingSenderId: '765957471616',
    projectId: 'fruit-hub-da7cf',
    storageBucket: 'fruit-hub-da7cf.firebasestorage.app',
    iosBundleId: 'com.example.fruitesECommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsuc30l3L6Fr69fxn73M-lT2WNDT22kLM',
    appId: '1:765957471616:web:d60fcad8a67a2c29d41565',
    messagingSenderId: '765957471616',
    projectId: 'fruit-hub-da7cf',
    authDomain: 'fruit-hub-da7cf.firebaseapp.com',
    storageBucket: 'fruit-hub-da7cf.firebasestorage.app',
    measurementId: 'G-E547BWETPW',
  );
}
